### ISSUE TITLE
Linkurious settings don't work

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#139]
I have a small test here: http://pastebin.com/ngauBFWg that I would expect to produce a graph with red edges and labels inside the node, neither of which happens.  what am I missing or what have I got wrong?

specifically I would expect this to work:

```
s.settings({
	labelAlignment: 'inside',
	edgeColor: 'default',
	defaultEdgeColor: '#ff0000'
});
```

but it doesn't.  help?

**Comment by sheymann** [comment]
Hello,

I can see labels inside the node when zooming in, but there is an issue with edge color: this is because the plugin sets edge colors individually:
https://github.com/Linkurious/linkurious.js/blob/linkurious-version/plugins/sigma.parsers.cypher/sigma.parsers.cypher.js#L102

I'm gonna fix it right now.

**Comment by ekkis** [comment]
ah.  there is an issue.  glad to hear it isn’t me.  for me the labels appear to the right of the node, regardless of the zoom level.  if you’d like to replicate my data, I can send you cypher

**Comment by sheymann** [comment]
Try with labelAlignment: 'center' instead because in that case the label will necessarily at the center of the node circle. The 'inside' setting will display the label at the center only if the node is big enough to contain the label. 

The reason of this setting is due to color contrasts: it is extremely difficult to create label colors with both high contrast to the node colors and to the background color, because node colors and background color should already have a high contrast.

**Comment by ekkis** [comment]
it seems to be a browser problem.  in Safari the labels are outside the node at any zoom level, but I just tried Chrome and that seems to render them correctly i.e. they’re outside the node at normal zoom level but when I zoom in the labels float inside.

I need to make my nodes larger but haven’t yet figured out how

**Comment by sheymann** [comment]
Set `minNodeSize` and `maxNodeSize` settings.

**Comment by ekkis** [comment]
ah.  now the labels render inside the node as they should, even in Safari

**Comment by ekkis** [comment]
haven’t seen you online on Skype.  chat some time?

**Comment by sheymann** [comment]
@ekkis I'm too busy today. Talk tomorrow 6pm CEST?

**Comment by ekkis** [comment]
just look me up when you have the time.  I'm online all the time

**Comment by MohammedFCIS** [comment]
Thank you @ekkis your issue resolved mine :+1:
