### ISSUE TITLE
plugins.legend

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#188]
Use sigma.plugins.design to generate a legend overlay displayed over the graph. The overlay can be visible in image exports (png, svg).

Legend content:

- node size
- edge thickness
- node icons
- edge shape/direction
- node color
- edge color
- node text
- edge text

Legend data comes from sigma.plugins.design.

Where should we position the legend? Should we provide options like top/bottom/left/right?

See inspiration here: http://d3-legend.susielu.com/

**Comment by sheymann** [comment]
![lkjs-legend-plugin](https://cloud.githubusercontent.com/assets/177962/10281561/8f8dccd0-6b75-11e5-9c31-3f76294a7398.png)

@Ytawo @davidrapin RFC

**Comment by davidrapin** [comment]
- what is "node text" and "edge text"?
- how does the user configure which legend panel is visible?
- how does the user specify the units for edge/node size?
- does the user choose the position of the legend panels?

**Comment by sheymann** [comment]
> what is "node text" and "edge text"?

It explains what text is displayed along nodes or edges, as it may be handcrafted or coming from a property.

> how does the user configure which legend panel is visible?

The plugin API should be designed so that each panel can be added individually.

> how does the user specify the units for edge/node size?

As an option for the related panel.

> does the user choose the position of the legend panels?

The user chooses the position for all panels at once (top/bottom/left or right side of the viz).

**Comment by Ytawo** [comment]
For "node text", since nodes of different categories can have different format (for example, I could choose to display only the name of the investors, and name + funding year for companies), how should it be handled? One line per category? If so, how is the user supposed to know which node belongs to which category if they don't have color or icon associated?

**Comment by davidrapin** [comment]
For now I'd say one line per category, even if categories are not differentiated graphically. Same goes for edges btw.

**Comment by Ytawo** [comment]
"Legends widgets have fixed width and flexible height", however in your example it seems that width and height are fixed or flexible depending on the position of the widgets (top & bottom -> flexible width, left & right -> flexible height).

**Comment by Ytawo** [comment]
The configuration of the number of rows and columns causes come problems:

* What if the user wants 1 column and 1 row?
* Generally speaking, the user is not in a good position to choose the number of rows and columns: widgets could have variable dimensions, which makes difficult for the user to determine the optimal configuration
* If there is enough space on one row to display every widget (for example), that wouldn't make sense to want two rows.

Same goes for the widget order of appearence: depending on the widget dimensions, the "optimal configuration" may not be possible by only configuring the ordering of widgets and the number of rows and columns. Let's say a user wants to display 4 properties: A, B, C and D, in that order.

![example](https://cloud.githubusercontent.com/assets/1114369/10363986/301a2f88-6db8-11e5-9da3-0cc3398a749f.png)


The second layout is probably what the user would like (small widgets are grouped), but he couldn't do better than the first layout with these options.

One simple solutions may be to allow the user to drag and drop the widgets so they can place them wherever they want (with an option to enable/disable the "legend editing"). Thoughts?

**Comment by sheymann** [comment]
I agree that the position would not necessarily be optimal, but I'd prefer have a suboptimal yet automatic positionning than requiring the end user to position each legend items manually. The reason is because the user target is not a designer, and may export dozens of visuals per day.

Legend should also consume the less space possible.

**Comment by sheymann** [comment]
The number of rows and columns could be calculated using a [bin packing algorithm](http://stackoverflow.com/questions/1213394/algorithm-needed-for-packing-rectangles-in-a-fairly-optimal-way) if we are looking for optimality.

However maybe a half-way solution would be to assign each legend item a position around the viz (top, bottom, left, right side, or finer e.g. top-left, top-center, top-right, etc.) so we can build an UI easy enough to use.

**Comment by Ytawo** [comment]
Some questions:
* In case the graph and the legend overlap, which one should be displayed above the other?
* Is it ok to have a method like "buildLegendWidgets", which must be called whenever there is a change in the graph design? (if not, maybe we could extend the design plugin so it calls the method itself?)
* Option to drag and drop widgets: needed feature? If so, should the "drag and dropping" be managed inside the plugin or outside of it? (should I only provide a function "changeWidgetPosition" or manage the whole thing inside the plugin)
* Widgets appearance: we need to discuss it (background color? border? etc)
* Text widgets: we also need to discuss it (how will they be used? for example, it would be way easier to let the user enter the text inside a modal window instead of directly "inside" the widget)

I also would like you to confirm the list of "base widgets", to make sure I don't forget one:
node size, node color, node icon, edge size, edge color, edge type (shape), edge direction.

**Comment by sheymann** [comment]
>In case the graph and the legend overlap, which one should be displayed above the other?

The legend, as it is necessary to read the graph.

>Is it ok to have a method like "buildLegendWidgets", which must be called whenever there is a change in the graph design? (if not, maybe we could extend the design plugin so it calls the method itself?)

Yes I don't see the need for coupling both plugins at the moment.

>Option to drag and drop widgets: needed feature? If so, should the "drag and dropping" be managed inside the plugin or outside of it? (should I only provide a function "changeWidgetPosition" or manage the whole thing inside the plugin)

>Widgets appearance: we need to discuss it (background color? border? etc)

Keep it minimal: white background, no border.

>Text widgets: we also need to discuss it (how will they be used? for example, it would be way easier to let the user enter the text inside a modal window instead of directly "inside" the widget)

Consider the API only, the UI should not be handled by the plugin to ease integration of the lib.

**Comment by Ytawo** [comment]
I need your opinion: when displaying the types of edge, how should I specify the direction of the egde? Currently I do this: 
![screenshot - 15102015 - 14 38 50](https://cloud.githubusercontent.com/assets/1114369/10513852/a916d2fa-734a-11e5-91d2-ca9b8e95fdcd.png)

but I'm not sure if it's explicit enough. I can't really put "Source" and "Target" at each edge boundary since it would take way too much space.

**Comment by sheymann** [comment]
Look good! maybe say "source node to target node" as subtitle.

Also "relation" does not mean what you think :) Say "relationship" (beark) or "edge". I used to say "link" but found it confusing for some people.

**Comment by sheymann** [comment]
- [ ] `sigma.plugins.legend(sigmaInstance).exportPng()` returns an empty file because if `draw() is not called before
- [ ] the exported SVG cannot be displayed if opened in a browser tab. Notice that it displays well in Inkscape.
- [ ] If the legend is not drawn yet and we call `exportPng` or `exportSvg`, the legend should be rendered off screen.

**Comment by sheymann** [comment]
- [ ] The plugin should listen to the sigma `kill` event, and call `sigma.plugins.killLegend` in that case. Example: https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.plugins.filter/sigma.plugins.filter.js#L589

**Comment by sheymann** [comment]
- [ ] legendBorderWidth: 0 should hide the border, instead of displaying a border of width 1

**Comment by sheymann** [comment]
- [ ] Formatting error in title: "first_funding_at" should be "First funding at"

![image](https://cloud.githubusercontent.com/assets/177962/10818595/32378bf8-7e43-11e5-8a81-92522fac114b.png)

**Comment by sheymann** [comment]
- [ ] It's more common to list large values on top, to small values on bottom. The following is the opposite, can you fix it for both nodes and edges colors?

![image](https://cloud.githubusercontent.com/assets/177962/10818738/30abb5ba-7e44-11e5-85a4-1ae797ab2b7c.png)

**Comment by sheymann** [comment]
- [ ] important bug on Retina display: wrong pixel ratio, the legend is blurred and larger than what it should be. Related to #25
