### ISSUE TITLE
Rename sigma.layout.* -> sigma.layouts.*

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#239]
Add 's' to `layout` package for consistency.

**Comment by davidrapin** [comment]
@sheymann @Ytawo Guys, in the future just know that Linkurious-client and Linkurious-server builds use the develop branch of Linkurious.js. 

We are currently releasing Linkurious Enterprise 1.0 and this broke the build because it requires updates in linkurious-client. Don't do this during release processes (a.k.a **don't break develop while we're in the process of releasing**). It's difficult enough to squash existing bugs without adding new ones.

**Comment by Ytawo** [comment]
Ok sorry about that.
