### ISSUE TITLE
Node and Label overlap after FA2

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#290]
We are using the Linkurious version of FA2 (since the sigma version changed in the last big release of linkurious) and we've been struggling with a serious problem of overlapping nodes and labels.

When I generate the data for the graph, I have a randomizing script that spreads all the nodes out across the entire area of the graph (width/height). No single node is in the same place. Then the force function is run on the data and it moves everything into an "organized" graph but there's a ton of overlap with the nodes and the labels. I've been trying to find a solution, but I'm hoping someone else has found a way to do this. On desktop systems, using Gephi, there's a prevent overlap toggle. Is there such an option?

I've tried the adjustSize setting and that just makes so much worse.

See the example screenshot.
![node and label overlap](https://cloud.githubusercontent.com/assets/1018133/10519599/36e6d48e-731b-11e5-86f8-29d0ea9380b1.jpg)

**Comment by sheymann** [comment]
Hi, there's no solution yet but it could be great to develop a plugin similar to [Noverlap](https://marketplace.gephi.org/plugin/noverlap/) in Gephi. Keep in mind that it will be a very costly algorithm.

**Comment by audvin** [comment]
Current layout creates a lot of noise and it's hard to "read" the graph without putting quite a bit of effort of drag and drop in the graph. 

Perhaps such a overlap prevention plugin can run immediately after the FA2 plugin has stopped?

There are 3 areas where overlap is an issue (in prioritized order):
1. Node overlap
2. Node label overlap
3. Node overlap with edges

Doesn't have to be perfect, but some improvement would be warmly welcomed.

**Comment by sheymann** [comment]
Hello, most overlapping issues can be fixed with proper settings of sigma.js. My advices:

- Use a good web font such as [Roboto Regular](https://www.google.com/fonts/specimen/Roboto) and set the smallest size of the font possible so that it is still readable.
- Don't map font size with node size, or you end up with large texts that will clutter the visualization.
- Display labels at node center with the setting `labelAlignment: 'center'` so that (node+label) consumes less pixels.

**Comment by sheymann** [comment]
Closed due to inactivity
